### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'model_type'

### ISSUE THREAD

**Issue by amin-sagar** [ComputationalBiologyLab-IIITH/HYDRA#2]
Hello.
Thanks for this amazing work.
I tried to run the example scripts but I got
```
(HYDRA) :~/softwares/HYDRA$ python3 scripts/sample-pdb.py data/pfemp1/PF3D71150400_MEDIUM.pdb configs/train.yml configs/sample.yml --out_dir ./outputs
Loading config...
Seed set to 2023
Preparing data...
Traceback (most recent call last):
  File "scripts/sample-pdb.py", line 117, in <module>
    Fire(main)
  File "/home/amin/mambaforge/envs/HYDRA/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/amin/mambaforge/envs/HYDRA/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/amin/mambaforge/envs/HYDRA/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "scripts/sample-pdb.py", line 77, in main
    model = TARP.load_from_checkpoint(
  File "/home/amin/mambaforge/envs/HYDRA/lib/python3.8/site-packages/pytorch_lightning/utilities/model_helpers.py", line 125, in wrapper
    return self.method(cls, *args, **kwargs)
  File "/home/amin/mambaforge/envs/HYDRA/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1581, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/amin/mambaforge/envs/HYDRA/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 91, in _load_from_checkpoint
    model = _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/amin/mambaforge/envs/HYDRA/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 158, in _load_state
    obj = cls(**_cls_kwargs)
  File "/home/amin/softwares/HYDRA/models/tarp.py", line 30, in __init__
    self.model = ScorePosNet3D(
  File "/home/amin/softwares/HYDRA/models/molopt_score_model.py", line 325, in __init__
    self.refine_net_type = config.model_type
AttributeError: 'EasyDict' object has no attribute 'model_type'
```
I can't find what the value of model_type should be set to.
I would be really grateful for any suggestions.
Best,
Amin.

**Comment by amin-sagar** [comment]
Update:
I tried commenting out the line
self.refine_net_type = config.model_type
as it didn't seem to be used anywhere else in the code. This allows the sampling step to complete but peptide reconstruction step throws the following errors and no peptides are generated.

```
024-09-12 06:18:22,103 - pyswarms.discrete.binary - INFO - Optimize for 100 iters with {'c1': 2.5, 'c2': 0.5, 'w': 0.9, 'k': 1.8, 'p': 2}t/s]
                                                                                                                                            [06:18:22] Incomplete atom labelling, cannot make bond
[06:18:22] Molecule does not have explicit Hs. Consider calling AddHs()                                                                |0/100
[06:18:22] Incomplete atom labelling, cannot make bond
[06:18:22] Molecule does not have explicit Hs. Consider calling AddHs()
[06:18:22] Incomplete atom labelling, cannot make bond
[06:18:22] Molecule does not have explicit Hs. Consider calling AddHs()
[06:18:22] Incomplete atom labelling, cannot make bond
[06:18:22] Molecule does not have explicit Hs. Consider calling AddHs()
[06:18:22] Incomplete atom labelling, cannot make bond
[06:18:22] Molecule does not have explicit Hs. Consider calling AddHs()
[06:18:22] Incomplete atom labelling, cannot make bond
[06:18:22] Molecule does not have explicit Hs. Consider calling AddHs()
[06:18:22] Incomplete atom labelling, cannot make bond
[06:18:22] Molecule does not have explicit Hs. Consider calling AddHs()
[06:18:22] Incomplete atom labelling, cannot make bond
[06:18:22] Molecule does not have explicit Hs. Consider calling AddHs()
pyswarms.discrete.binary:   0%|                                                                                                        |0/100
Failed to reconstruct (49).
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:21<00:00,  2.34it/s]
Sucessfully reconstructed 0 peptides.████████████████████████████████████████████████████████████████████████| 50/50 [00:21<00:00,  2.97it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [02:52<00:00, 43.05s/it]
Done!
```
Best,
Amin

**Comment by luckyqin2002** [comment]
Just a typo—changing model_type to model_mean_type fixed the issue, but be prepared for many more bugs ahead. Looks like I’m done with this tool. 😅
